### ISSUE TITLE
Facets in web app don't have "more" link

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#120]
I noticed that the "Departments" facet in the browse section of the website doesn't appear to show all the values (presumably the list is quite long) but also doesn't show a "more" link for the modal lightbox selector for the full list (typical of blacklight)

**Comment by jcoyne** [comment]
This front end is not blacklight, it is a custom front end for Rialto that was built off the mockups that Astrid made.  As the mockups show all the departments, it was the intention to follow that here.

**Comment by peetucket** [comment]
Ahh, ok so no blacklight...but shouldn't the department list should be longer than what is currently shown?

**Comment by jcoyne** [comment]
@peetucket yep, See #122 for that fix

**Comment by jcoyne** [comment]
@peetucket blacklight is doing the searching and providing the search results to a JSON API which is in turn consumed by a frontend written in VueJS.

**Comment by jcoyne** [comment]
Department facet is now showing all departments.
