### ISSUE TITLE
Bad characters in countries_label_ssim

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#148]
See "Romania" :

https://rialto.dev.sul.stanford.edu/#/catalog/f%5Bcountries_label_ssim%5D%5B%5D=Rom%EF%BF%BDnia&q=

**Comment by justinlittman** [comment]
![2018-11-02_1137](https://user-images.githubusercontent.com/588335/47925140-ca46da80-de93-11e8-95aa-5bc41ac784fe.png)

**Comment by justinlittman** [comment]
And in Solr:
![2018-11-02_1138](https://user-images.githubusercontent.com/588335/47925198-f2363e00-de93-11e8-85a4-bb384096be90.png)

**Comment by justinlittman** [comment]
But not the Sparql:
![2018-11-02_1139](https://user-images.githubusercontent.com/588335/47925248-1560ed80-de94-11e8-8b4a-39a0138e776d.png)

**Comment by justinlittman** [comment]
Incorrect in BlazeGraph:
![screen shot 2018-11-02 at 11 41 58 am](https://user-images.githubusercontent.com/588335/47925377-6670e180-de94-11e8-89e0-ca56e730a5da.png)

**Comment by justinlittman** [comment]
Same when I write directly to BlazeGraph, bypassing Sparql Loader.

**Comment by justinlittman** [comment]
The problem is that ETL is not correctly setting the charset in content-type header and sparql-loader doesn't handle charset provided in a content-type header.
