### ISSUE TITLE
The Cross-Disciplinary Research Report is not showing any data

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#157]

**Comment by justinlittman** [comment]
@peetucket Can you provide some more context? It is working in my local dev environment:
![screen shot 2018-11-06 at 3 07 31 pm](https://user-images.githubusercontent.com/588335/48090751-c8ec1980-e1d5-11e8-8ae7-97161c63df76.png)

**Comment by jcoyne** [comment]
It's now fixed in production after the latest deploy. It wasn't working this morning.
