### ISSUE TITLE
Change how school/department filters work on collaboration reports and research trends report

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#169]
The collaboration report and the research trends report currently have two drop down menus, one for school and one for department, that are mutually exclusive.  A radio button would be make it clearer that these options are exclusive and would allow for a third filter selection, which is "All of Stanford" (implying institution = "Stanford").

So the UI would be:

Filter by 

( x ) School:  [ Drop down here ]
( ) Department: [ Drop down here ]
( ) All of Stanford

**Comment by peetucket** [comment]
We talked about a UI change to the filtering mechanism, thoughts @astridu ?

See https://rialto.dev.sul.stanford.edu/#/research-trends-report and https://rialto.dev.sul.stanford.edu/#/reports for how they currently work

**Comment by astridu** [comment]
@peetucket I can't access the links. I get an error.

**Comment by jcoyne** [comment]
@astridu you must sign into the "full traffic" VPN in order to see the site. See https://uit.stanford.edu/service/vpn for directions

**Comment by astridu** [comment]
I am connected to the VPN and still cannot see the pages.

**Comment by astridu** [comment]
Aha, that was it. Here are my suggestions:

1. When you select the 'school', the 'departments' pull down filters down to the departments in that school. 
2. Alternately, you could have one drop down, and then have the 'schools' each have submenus that display the departments associated with it when you hover over the school.
3. Another option (although this is less preferable), is to have 1 drop down menu, but it's organized by school. So you would display the school and then list all the associated departments under it. It's still one large list, but at least there would be a little organization to it.

Your thoughts?

**Comment by jcoyne** [comment]
Currently the webapp doesn't have the data to support any hierarchical modeling of school->department.  If that's required we'll need a corresponding ticket in rialto-derivatives

**Comment by peetucket** [comment]
I think #1 is probably the best/fastest approach, but it still doesn't get us an "all stanford" option.  Thoughts on the radio button idea i put in the original description ?

**Comment by astridu** [comment]
I created 3 options here: https://invis.io/9XNH4B1ZPVC#/330912122_dropdown_Options_1
Option 1a is the radio button idea combined with my suggestion #1 above.
Option 1b is the radio button idea with my suggestion #2 above (the cascading menus).
Option 2 is just one big pull down with the first option as 'All schools' and then there are cascading menus for each of the schools to be able to select the departments in that school, or you can just select the whole school.

**Comment by peetucket** [comment]
So I think option 1a is the most reasonable, the only concern is that users be able to select one or the other of school/department.  For example, I should be to select any of the following as a filter:

1. All of stanford (ok, radio button)
2. All of School of Engineering (would I just leave department unselected in your option 1a?)
3. Specific department in school engineering (select School of Engineering first, then select specific department from other drop down?)

**Comment by astridu** [comment]
2. Yes, you could either leave department unselected or have that dropdown automatically select 'All departments' when you select a department as the default, and then the user can change it to a specific department if they want.
3. Yes
