### ISSUE TITLE
Paginate the collaboration by co-author report

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#177]
This view of the data could have many many rows and should be paginated

Requires https://github.com/sul-dlss/rialto-webapp/issues/236

**Comment by jcoyne** [comment]
I don't understand the motivation for this.  Why do we want this to be paginated?  Spreadsheet software does not paginate a long spreadsheet, is this different from that?

**Comment by peetucket** [comment]
The motivation is that this table shows multiple rows per paper (potentially) and thus could get very very big, making the web page take too long to render (or impossible to render).  If we don't do pagination, we should least limit the rows rendered in the browser (maybe a few hundred?), clue to the user in to the fact that the data is truncated.   The download link would always provide the full dataset in that scenario.

**Comment by jcoyne** [comment]
@peetucket we have the webpage rendered before we download the CSV data, so that's not a reason we need to care about.  I think that limiting the data we are showing is can only be a disservice to the user.

**Comment by peetucket** [comment]
So does this mean both the CSV and HTML versions are constructed prior to rendering the page? What happens if the table has something like 100k rows or more?  The user needs to wait for the whole thing to be constructed as HTML and CSV, wait for the page to be shipped over HTTP and then rendered by the browser before they get the download link?  In the case of lot of data, the data is likely to be far more useful as a downloaded file vs HTML data anyway, so I'm not sure limiting the display is really a problem if it leads to them getting a rendered page with a download link much faster.  Display of all data is something that could be optimized later if needed (e.g. infinite scroll via ajax, paging, other options) but I'm worried that large data sets rendered as HTML may lead to effectively blocking users from even being able to get a CSV.  Or am I misunderstanding?

**Comment by jcoyne** [comment]
The CSV is created in real time.  The HTML is created on the page from the CSV after the page has loaded by javascript.  The D3 library does all of this loading and rendering for us, so we don't really have a way to adjust this without building this functionality ourselves and discarding D3.  Do we have any report currently that can display this pathological behavior?

**Comment by peetucket** [comment]
Blocked by sul-dlss/rialto#125

need more data to validate

**Comment by jcoyne** [comment]
Blocked by 236

**Comment by justinlittman** [comment]
closed by https://github.com/sul-dlss/rialto-webapp/pull/245
