### ISSUE TITLE
Update terminology of labels

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#178]
Filter labels and column labels in reports should be updated as follows:

- [x]  "Concept" --> "Topic area" in "Cross-Disciplinary Research Report" report drop down
- [x] "Concept" --> "Topic area" in facet label for browse

Can leave "department" as is for now (since it is now separated from Schools)

**Comment by justinlittman** [comment]
Assigning this to you, @peetucket so that can determine label for Department.
