### ISSUE TITLE
Add the ability to search by grant indentifier (agreement_number) from browse search box

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#180]
Are we indexing the external grant number (the one we use to link to WoS publications) in such a way that it can be searchable from the browse search box?

Requires sul-dlss/rialto-derivatives#153

**Comment by justinlittman** [comment]
@peetucket Do you want this implemented? If so, we can make it happen.

**Comment by peetucket** [comment]
Yes, I am confident this will be useful to stakeholders
