### ISSUE TITLE
Don't display Publications label when no publications

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/rialto-webapp#203]
![screen shot 2018-11-09 at 4 50 15 pm](https://user-images.githubusercontent.com/588335/48290108-d0166000-e43f-11e8-8389-6a75406c55ec.png)

**Comment by jcoyne** [comment]
I suspect you're going to find this one particularly challenging.

**Comment by jcoyne** [comment]
It would actually be a lot easier to have `Publications: none` rather than not showing anything.
