### ISSUE TITLE
Add beta badge to Rialto icon in header

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#224]

**Comment by astridu** [comment]
Yes, I'm assuming you want something to indicate that the software is in beta?

**Comment by peetucket** [comment]
that's right

**Comment by astridu** [comment]
Here are a couple options
![image](https://user-images.githubusercontent.com/42216982/48729660-ffba2a80-ebec-11e8-9c89-7f3334f9facd.png)
![image](https://user-images.githubusercontent.com/42216982/48729672-047ede80-ebed-11e8-9650-d7c362f96629.png)

**Comment by astridu** [comment]
Is that noticeable enough? Does it need to be bolder/more apparent? I could introduce color if needed.

**Comment by astridu** [comment]
I used color in the bookmark. I think this one looks better. 
![betabadge_sketch](https://user-images.githubusercontent.com/42216982/48731670-6beb5d00-ebf2-11e8-9ec8-222fd118965c.png)
