### ISSUE TITLE
Co-author report can not be generated quickly

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-webapp#236]
The co-authors report by school (http://rialto.dev.sul.stanford.edu/reports/coauthors.csv?org_uri=http://sul.stanford.edu/rialto/agents/orgs/school-of-medicine&start_year=2000&end_year=2018) can not be generated by the server in a reasonable time, which leads to a 504 Gateway timeout

The database itself is taking ~82 seconds to generate the report.

Some options to consider:
* We could increase the load balancer timeout from 60s to 90s, but I suspect this only kicks the problem down the road.
* We could increase RDS instance size (currently db.t2.medium)
* We could build some sort of background job processing.
* We could make a simpler report.
* Caching might help, but we'd still likely get a 504 on the cache miss. (at least the first time)

**Comment by peetucket** [comment]
This problem is likely to be worse than current too, since -dev does not even have all of the publications yet.  Let's discuss some strategies as a team -- perhaps simplifying or caching report with specific options preselected.

**Comment by cmh2166** [comment]
Where is the bottleneck? Is it a bunch of joins within RDS?

**Comment by justinlittman** [comment]
@cmh2166 The primary problem is the size of the report (one row for every author-coauthor combination).

#242 made the report more efficient. Even so, the size of the report is still likely to be problematic. (Not sure if this has been deployed yet.)

**Comment by jcoyne** [comment]
Now (after adding indexes) the report finished in 7s.  That seems reasonable.

```
time curl "https://rialto.dev.sul.stanford.edu/reports/coauthors.csv?org_uri=http://sul.stanford.edu/rialto/agents/orgs/school-of-medicine&start_year=2000&end_year=2018"
...
real	0m7.005s
user	0m0.150s
sys	0m0.065s
```

**Comment by peetucket** [comment]
Great!
