### ISSUE TITLE
Change ALB on :80 from "forward" to "redirect"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-webapp#240]
So that we redirect all port 80 traffic to HTTPS.

<img width="1203" alt="screen shot 2018-11-20 at 7 29 35 am" src="https://user-images.githubusercontent.com/92044/48776682-1ff1f400-ec96-11e8-8119-889531c5a400.png">

**Comment by aaron-collier** [comment]
This is going to take some manual work, or updates to the upstream module. I'll take a look and see if it's relatively easy without impacting anything else using the module.

**Comment by aaron-collier** [comment]
done.
