### ISSUE TITLE
Add type total counts to header/top nav

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#244]
It might be nice to show how much data is in the site somewhere in the header, e.g. 

110,00 people
320,000 publications
3245 grants

Maybe over by the beta badge in the red top header or the grey nav bar, but right justified?

**Comment by jcoyne** [comment]
This doesn't feel critical for this phase of work.  Was it something the users asked for?

**Comment by peetucket** [comment]
Its a bit of marketing, but effective (i've used similar things in previous projects and it was well received)

**Comment by mjgiarlo** [comment]
Keep in backlog or move to ready, @peetucket?

**Comment by peetucket** [comment]
I think this is a (potentially easy) improvement, but not critical for this workcycle.  Will move to bottom of ready.
