### ISSUE TITLE
Clear "Search" area after user clicks "Start Over"

### ISSUE THREAD

**Issue by vivnwong** [sul-dlss/rialto-webapp#255]
In the webApp, Browse section:
- Type in “Linked Data”, the app showed the result of the search
- Click the “Start Over” button, the app showed result for all data but search area still showed “Linked Data”. We should clear the Search area when the user clicks “start over”.

**Comment by justinlittman** [comment]
closed by https://github.com/sul-dlss/rialto-webapp/pull/256
