### ISSUE TITLE
Add a disclaimer to the header or  footer

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#257]
"Note: this is an internal Stanford system and data should be considered confidential.  Contact us via the feedback link if you would like to use the data publicly."

**Comment by peetucket** [comment]
NOTE: exact language to be confirmed...hold for now

**Comment by peetucket** [comment]
@astridu thoughts on how this might look?

**Comment by justinlittman** [comment]
@peetucket @astridu How about this?
![2018-11-28_0905](https://user-images.githubusercontent.com/588335/49157000-c2d8ec80-f2ec-11e8-91d7-b2b1ff7eb715.png)
