### ISSUE TITLE
Add "Feedback" link with a mailto: link for the web app

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#258]
email address is rialto-contact@lists.stanford.edu

link could be in header or footer

Per Tom: can be modeled on other projects like searchworks' feedback form, which pops down and sends to email.  Tom suggests we can just take the code and is thus easy, but understand if it might not be.  Given this is an internal app, we could alternatively do a simple mailto: link and backlog the actual form.

**Comment by justinlittman** [comment]
@peetucket How about this using a mailto instead of form?
![2018-11-28_0915](https://user-images.githubusercontent.com/588335/49157641-447d4a00-f2ee-11e8-8d4c-d2815d63465f.png)

**Comment by jcoyne** [comment]
Argo uses a mailto: link as @justinlittman has suggested.  Spotlight has no Feedback form.  If we must  have a form, then we need to set up an SMTP gateway, which would add complexity.

**Comment by peetucket** [comment]
Let's just do a mailto: link for expendiency, I'll create a backlog issue for the actual form for some future workcycle (and explain to Tom if it comes up).
