### ISSUE TITLE
Make beta badge more prominent

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#259]
@astridu as per a discussion with Tom this afternoon, he'd like the beta logo more prominent and over on the left hand side near the RIALTO logo

**Comment by justinlittman** [comment]
@peetucket How is this?
![2018-11-28_0812](https://user-images.githubusercontent.com/588335/49154052-6c1be480-f2e5-11e8-85cf-c420cf634e82.png)

**Comment by vivnwong** [comment]
I have suggested to move the current "Beta" to the left, but Tom still wants to see RIALTO Beta call out. But I think we can keep the above and convince him.

**Comment by astridu** [comment]
Looks like this issue is closed, but here are 2 other options just in case.

![image](https://user-images.githubusercontent.com/42216982/49249029-0e17fb80-f3d0-11e8-9a03-7aa6352033bb.png)

![image](https://user-images.githubusercontent.com/42216982/49249045-1c661780-f3d0-11e8-8fc2-c42a7226da8d.png)

**Comment by peetucket** [comment]
thanks, useful to have these as alternates if Tom wants more changes
