### ISSUE TITLE
Make BETA label giant somehow

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-webapp#324]
Tom wants the Beta label really big.

**Comment by justinlittman** [comment]
How about this?
<img width="507" alt="screen shot 2019-02-04 at 10 35 53 am" src="https://user-images.githubusercontent.com/588335/52218520-d6fb1600-2868-11e9-8ff8-168f6400e4cb.png">

**Comment by justinlittman** [comment]
Prominent, but not giant. @peetucket?
