### ISSUE TITLE
Display is broken after the 2.7 ruby update

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/rialto-webapp#435]
... more to come.

**Comment by jcoyne** [comment]
I'm seeing `ArgumentError: Missing 'secret_key_base' for 'production' environment` is that what you see?

**Comment by aaron-collier** [comment]
I did not see that, but could explain it. However, I would have expected an error in the display vs. blank...

**Comment by jcoyne** [comment]
I don't think the server ever starts without that.  It works if I do:
```
docker run -p 3000:3000 -e SECRET_KEY_BASE=R6Q3bUqMh45hy83UPLPDwDP+R1oMOH6WBwv0 suldlss/rialto-webapp:latest
```

**Comment by aaron-collier** [comment]
Huh, it looks like we've only used `RAILS_MASTER_KEY` for a while now. I'll set `SECRET_KEY_BASE` in terraform and see what happens.

**Comment by jcoyne** [comment]
@aaron-collier we shouldn't have to as rails_master_key is encoded within config/credentials.yml.enc

**Comment by aaron-collier** [comment]
Yeah, that didn't seem to change anything.
