### ISSUE TITLE
Implement the ability to filter by topic in the "cross-disciplinary research report" (RIALTO-15)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-webapp#62]

**Comment by justinlittman** [comment]
@peetucket Is this done?
![screen shot 2018-11-06 at 3 19 14 pm](https://user-images.githubusercontent.com/588335/48091337-6562eb80-e1d7-11e8-854a-7bfeaec1513e.png)

**Comment by jcoyne** [comment]
@justinlittman I think so, this ticket was opened a long time ago.
