### ISSUE TITLE
Implement the ability to filter by year in the "cross-disciplinary research report" (RIALTO-15)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-webapp#63]

**Comment by justinlittman** [comment]
@peetucket Wondering if this is necessary? Since each year is a separate column, is there value in filtering by years?
![screen shot 2018-11-06 at 3 15 38 pm](https://user-images.githubusercontent.com/588335/48091147-e79ee000-e1d6-11e8-862c-3ba53f0b2528.png)

**Comment by peetucket** [comment]
I think the challenge is that as the number of years of data grow, this table will become very wide.  But that's not a blocker for now so this can be deprioritized

**Comment by justinlittman** [comment]
Closing for now. Can re-open if proves necessary.
