### ISSUE TITLE
Implement the ability to filter by topic area for the "research trends by topic" report (RIALTO-13)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-webapp#67]

**Comment by peetucket** [comment]
Similar to https://github.com/sul-dlss/rialto-webapp/issues/63#issuecomment-436406342, as the list of topics becomes longer, this table grows bigger and bigger.  But again, can be deprioritized

**Comment by justinlittman** [comment]
Closing for now.
